[workspace]
members = ["app", "lab", "lab/sameboy-sys", "lib", "server"]
default-members = ["app", "lib", "server"]
resolver = "3"

[workspace.package]
version = "0.6.0"
edition = "2024"
license = "MIT"
homepage = "https://gb.lemon.industries"
repository = "https://github.com/Zitronenjoghurt/citrine-gb"

[workspace.dependencies]
citrine-gb = { path = "lib" }

[profile.dev.package.sameboy-sys]
opt-level = 3
